### ISSUE TITLE
Amazon AWS API Gateway support

### ISSUE THREAD

**Issue by umair-khokhar** [Shopify/shopify-node-api#155]
## Overview
I am working on using a AWS lambda function (which is behind a API gateway route). I created a mocked IncomingMessage and ServerResponse object using node-mocks-http. I am using [Serverless](https://www.serverless.com/) framework.

Can we add support for AWS API gateway, AWS Lambda, and Serverless framework?

## Type

- [ ] New feature

## Motivation
My code

```
 export const getAuth = async (event: any): Promise<any> => {
  try {
    Shopify.Context.initialize({
        API_KEY: String(process.env.SHOPIFY_API_KEY),
        API_SECRET_KEY: String(process.env.SHOPIFY_API_SECRET),
        SCOPES: String(process.env.SHOPIFY_API_SCOPES).split(","),
        HOST_NAME: String(process.env.SHOPIFY_APP_URL).replace(/https:\/\//, ""),
        API_VERSION: ApiVersion.October20,
        IS_EMBEDDED_APP: true,
        SESSION_STORAGE: new Shopify.Session.MemorySessionStorage(),
    });


    const request:any = httpMocks.createRequest({
      method: event.httpMethd,
      url: event.resource,
      params: event.pathParameters,
    });
    console.log(request);

    const response = httpMocks.createResponse();

    try {
      const authRoute = await Shopify.Auth.beginAuth(request, response, SHOP, '/auth/callback');

      return reply({ 'Location': authRoute }, httpStatuses.MOVED_TEMPORARILY);
    }
    catch (e) {
      console.log(e);
      return replyError(e);
    }

    
    
  } catch (e) {
    return replyError(e);
  }
};

export function handler(event, context):any {
  const collectionHandlers = {
    POST: null,
    GET: getAuth,
  };
  const itemHandlers = {
    PUT: null,
    DELETE: null,
  };

  return router(collectionHandlers, itemHandlers, { event, context });
}
```

I am getting the following response 

```
TypeError: Cannot set property 'set-cookie' of undefined
    at EventEmitter.setHeader (_http_outgoing.js:556:31)
    at Cookies.set (/Users/umair/Desktop/code/shopify/category_management/backend/node_modules/cookies/index.js:116:13)
    at Object.<anonymous> (/Users/umair/Desktop/code/shopify/category_management/backend/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:55:33)
    at step (/Users/umair/Desktop/code/shopify/category_management/backend/node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/umair/Desktop/code/shopify/category_management/backend/node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/umair/Desktop/code/shopify/category_management/backend/node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-31 19:05:10 [error]: TypeError: Cannot set property 'set-cookie' of undefined 
```

---

## Checklist

- [ ] I have described this feature request in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hey @umair-choudhary, I believe the error you're seeing is because `Shopify.Auth.beginAuth` needs to set a cookie to be able to store some information it needs to complete the OAuth process, and we use the `cookies` package to do that.

The cookies package will try to set the `set-cookie` header in your response object, which your server would need to forward in this case for things to work as expected. Given that the error happens when trying to set that property, you may be able to work around this by adding an empty `headers` hash to your mock response.

Would you be able to set a cookie in your `reply` call if the library provided a `setCookie` callback argument to `beginAuth` which overrides the default behaviour? That's something we could look into doing.

**Comment by hand-dot** [comment]
@umair-khokhar  @paulomarg 

It's a bit of a hack, but I was able to solve this problem by setting the set method to undefined after creating the response.

```
    const response = httpMocks.createResponse();
    response.set = undefined; // <-
```
