### ISSUE TITLE
storeCallback of CustomSessionStorage has id as "offline_" -> shop id missing 

### ISSUE THREAD

**Issue by luciilucii** [Shopify/shopify-node-api#222]
# Issue summary
When trying to redirect the merchant to a charge url, the session in the store callback doesn't have a shop value, and the id is "offline_". The shop is actually an empty string in that case. I only use `loadCurrentSession` in our subscription logic.

I use both offline and online authentication. Here's more about how I'm using this:
https://github.com/Shopify/koa-shopify-auth/issues/106

## Expected behavior
The merchant should be redirected to the charge url.

## Actual behavior
I get an "empty" session in my storeCallback function. Therefore I cannot save it the right way. When I redirect the user to the payment page, I get a "Bad request". 

    session id here Session {
        id: 'offline_',
        shop: '',
        state: '205211064309703',
        isOnline: false
    }

Here's a request id of a request where this happened:

    request_id=8aa8431a-e7ad-4d52-9938-3bd90357828c 

Here is the trace of the error:

    at CustomSessionStorage.storeCallback (/Users/.../server/sessionHandler.js:44:27)
    at CustomSessionStorage.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:23:51)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:124:57)
    at /Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:113:16)
    at CustomSessionStorage.storeSession (/Users/.../node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:17:24)
    at Object.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:49:80)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at CustomSessionStorage.storeCallback (/Users/.../server/sessionHandler.js:47:25)
    at CustomSessionStorage.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:23:51)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:124:57)
    at /Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:113:16)
    at CustomSessionStorage.storeSession (/Users/.../node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:17:24)
    at Object.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:49:80)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)

## Steps to reproduce the problem
I'm not really sure how to reproduce the problem. It seems very random. It just happens sometimes. 

Here's what's **not** causing the issue:
[X] Admin/Employee account doesn't seem to matter. I also have the issue on admin accounts
[X] Reinstalling the app doesn't solve the problem
[X] Using a different ngrok link/restarting the server both didn't solve the issue
[X] Local/production environment -> happened on both ends...
[X] A combination of all three doesn't solve the issue

In the past I just had to wait to let the issue resolve itself. 

## Other
I previously posted the issue this package, I wasn't sure what was causing the issue:
https://github.com/Shopify/koa-shopify-auth/issues/111

**Comment by luciilucii** [comment]
Hey, sorry for my late response! 
I've double-checked everything. There was an error on my server when the session timed out. Therefore I couldn't load the current session. 
That lead to an error in my graphql call to get the charge URL and I was redirecting the user to `undefined` in my react page. Then I got the "empty" session. 

Long story short: I fixed the error and now everything works fine! :)
