### ISSUE TITLE
"Could not find an OAuth cookie for shop url" error in OAuth example from the documentation

### ISSUE THREAD

**Issue by jedrzej-shopcat-io** [Shopify/shopify-node-api#297]
# Issue summary

I'm trying to install a Shopify app built with Next.js, deployed to Vercel. I added 2 routes, `/api/auth` and `/api/auth/callback` that use the sample code from the documentation here https://github.com/Shopify/shopify-node-api/blob/main/docs/usage/oauth.md, Note.js section, but I keep getting an error `Could not find an OAuth cookie for shop url`.

I saw a similar issue here https://github.com/Shopify/shopify-node-api/issues/130, but this issue was related with OAuth cookie expiration and was fixed in `koa-shopify-auth` package, which I am not using in my app. Moreover, expiration is not the case here - I've already approved required scopes, so after going to `/api/auth` and being redirected to Shopify, I get redirected back to `/api/auth/callback` immediately.

I've noticed that I do not see any cookies created for my app. Plus, i do not any code in the sample code that might be setting one, so I'm not really sure where that missing cookie should come from.

## Expected behavior

`Shopify.Auth.validateAuthCallback` in `/api/auth/callback` should not throw.

## Actual behavior

`Shopify.Auth.validateAuthCallback` throws an error 

<details>
2022-02-04T13:46:17.274Z	f374b939-13c5-473e-bb0b-ebd0ca237f4d	ERROR	CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: devsupplierstore1.myshopify.com
    at CookieNotFound.ShopifyError [as constructor] (/var/task/packages/sr/node_modules/@shopify/shopify-api/dist/error.js:13:28)
    at new CookieNotFound (/var/task/packages/sr/node_modules/@shopify/shopify-api/dist/error.js:148:42)
    at Object.<anonymous> (/var/task/packages/sr/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:96:35)
    at step (/var/task/packages/sr/node_modules/tslib/tslib.js:143:27)
    at Object.next (/var/task/packages/sr/node_modules/tslib/tslib.js:124:57)
    at /var/task/packages/sr/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/task/packages/sr/node_modules/tslib/tslib.js:113:16)
    at Object.validateAuthCallback (/var/task/packages/sr/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:83:24)
    at handler (/var/task/packages/sr/.next/server/pages/api/auth/callback.js:29:92)
</details>

## Steps to reproduce the problem

1. Create 2 routes in a Next.js app:
```
// GET /api/auth
import Shopify, { ApiVersion } from '@shopify/shopify-api';
import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { SHOPIFY_API_KEY, SHOPIFY_API_SECRET, SHOPIFY_SCOPES, SHOPIFY_APP_HOST } = process.env;

  Shopify.Context.initialize({
    API_KEY: SHOPIFY_API_KEY!,
    API_SECRET_KEY: SHOPIFY_API_SECRET!,
    SCOPES: SHOPIFY_SCOPES!.split(','),
    HOST_NAME: SHOPIFY_APP_HOST!,
    IS_EMBEDDED_APP: true,
    API_VERSION: ApiVersion.October21,
    SESSION_STORAGE: new Shopify.Session.MemorySessionStorage(),
  });

  const shop = req.query.shop as string;
  if (typeof shop !== 'string' || !Shopify.Utils.validateShop(shop)) {
    res.status(400).send('Invalid shop parameter');
    return;
  }

  const authRoute = await Shopify.Auth.beginAuth(req, res, shop, '/api/auth/callback', false);
  res.writeHead(302, { Location: authRoute });
  res.end();
}

// GET /api/auth/callback
import Shopify, { AuthQuery, ApiVersion } from '@shopify/shopify-api';
import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { SHOPIFY_API_KEY, SHOPIFY_API_SECRET, SHOPIFY_SCOPES, SHOPIFY_APP_HOST } = process.env;

  Shopify.Context.initialize({
    API_KEY: SHOPIFY_API_KEY!,
    API_SECRET_KEY: SHOPIFY_API_SECRET!,
    SCOPES: SHOPIFY_SCOPES!.split(','),
    HOST_NAME: SHOPIFY_APP_HOST!,
    IS_EMBEDDED_APP: true,
    API_VERSION: ApiVersion.October21,
    SESSION_STORAGE: new Shopify.Session.MemorySessionStorage(),
  });

  const session = await Shopify.Auth.validateAuthCallback(req, res, req.query as unknown as AuthQuery);

  const searchParams = new URLSearchParams(req.url);
  const host = searchParams.get('host');
  const shop = searchParams.get('shop');
  res.writeHead(302, { Location: `/admin?host=${host}&shop=${shop}` });
  res.end();
}
```

2. Go to `/api/auth`
3. Get redirected to Shopify store
4. Approve required scopes
5. Get redirected back to `/api/auth/callback`

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://webkit.org/test-case-reduction/).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by redochka** [comment]
which version of node shopify-api are you using (check your package.json)

**Comment by bishpls** [comment]
Cookie is originally set as part of beginAuth, here: https://github.com/Shopify/shopify-node-api/blob/770c9a837c4be025fee39615122f78017393f733/src/auth/oauth/oauth.ts#L72

Your error is coming from this line in validateAuthCallback failing to retrieve the session cookie: https://github.com/Shopify/shopify-node-api/blob/770c9a837c4be025fee39615122f78017393f733/src/auth/oauth/oauth.ts#L118

I'm not particularly familiar with using Next.js, but my guess would be the issue is you're re-establishing Shopify.Context.initialize on both routes; the cookie is initially created in beginAuth, you reset Context (wiping out the cookie and session, as you wiped out your original session storage) and validateAuthCallback has nothing to retrieve. Context should be an app-scoped object, not a request-scoped object.

**Comment by jedrzej-shopcat-io** [comment]
Ok, that must be it. I believe context is a request-scoped object in next.js.
