### ISSUE TITLE
🔴 Shopify API error on Cloudflare 🔴

### ISSUE THREAD

**Issue by joelket23** [Shopify/shopify-node-api#869]
- `@shopify/shopify-api` version:7.0.0
- `Node version`: 18
- `Operating system`: macOS M1

## Error
When I am trying to deploy my Next.js app on Cloudflare, I am getting an error message that says `'utils:node'`.
 

```./node_modules/@shopify/shopify-api/lib/auth/decode-host.js
▲  A Node.js API is used (Buffer at line: 8) which is not supported in the Edge Runtime.
▲  Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲  
▲  Import trace for requested module:
▲  ./node_modules/@shopify/shopify-api/lib/auth/decode-host.js
▲  ./node_modules/@shopify/shopify-api/lib/auth/get-embedded-app-url.js
▲  ./node_modules/@shopify/shopify-api/lib/auth/index.js
▲  ./node_modules/@shopify/shopify-api/lib/index.js
▲  ./component/backend/shopify_config.ts
```
## shopify_config.ts 
```Node.js
import '@shopify/shopify-api/adapters/cf-worker';
import {
  shopifyApi,
  ApiVersion,
  LATEST_API_VERSION,
  Shopify,
  BillingInterval,
  BillingReplacementBehavior,
} from '@shopify/shopify-api';
import { BillingConfig } from '@shopify/shopify-api/lib/billing/types';
import { AuthScopes } from '@shopify/shopify-api/lib/auth/scopes';
export const billingConfig: BillingConfig = {
  Basic: {
    amount: 1.49,
    currencyCode: 'USD',
    interval: BillingInterval.Every30Days,
    trialDays: 30,
  },
};

const scopes: string[] | AuthScopes = process.env.SCOPES
  ? process.env.SCOPES.split(',')
  : [];

export const shopify = shopifyApi({
  apiKey: process.env.API_KEY ?? '',
  apiSecretKey: process.env.API_SECRET_KEY ?? '',
  scopes,
  hostName: process.env.HOST ?? '',
  billing: billingConfig,
  hostScheme: 'https',
  apiVersion: ApiVersion.April23,
  isEmbeddedApp: true,
});
```

## Full log error ❌

I am getting an error on the building command (`npx @cloudflare/next-on-pages --experimental-minify`)
```Node.js
✘ [ERROR] Could not resolve "node:util"

    ../../../../../../../private/var/folders/nr/3ypdttb510x4t_w50n7j9kyw0000gn/T/snudmvq8zx/2476.js:1:50:
      1 │ export default e=>{"use strict";e.exports=require("node:util")}
        ╵                                                   ~~~~~~~~~~~

  The package "node:util" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
../../../../../../../private/var/folders/nr/3ypdttb510x4t_w50n7j9kyw0000gn/T/snudmvq8zx/2476.js:1:50: ERROR: Could not resolve "node:util"
    at failureErrorWithLog (/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/ketan kushwah/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 50,
        file: '../../../../../../../private/var/folders/nr/3ypdttb510x4t_w50n7j9kyw0000gn/T/snudmvq8zx/2476.js',
        length: 11,
        line: 1,
        lineText: 'export default e=>{"use strict";e.exports=require("node:util")}',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: `The package "node:util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.`
        }
      ],
      pluginName: '',
      text: 'Could not resolve "node:util"'
    }
  ],
  warnings: []
}
```

## Steps to produce the problem

1. Install `@shopify/shopify-api` package on `next js` 
2. import and config shopify api (like `shopify_config.ts`)
3. connect to cloud flare and use `npx @cloudflare/next-on-pages --experimental-minify`

**Comment by chr33s** [comment]
@joelket23 had the same issue, upgrading to 7.1.0 fixed it for me.
